{{- if .Values.integrationTesting.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "supaglue.componentname" (list . "integration-testing") }}
  labels:
    app.kubernetes.io/name: {{ include "supaglue.name" . }}
    helm.sh/chart: {{ include "supaglue.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ default .Chart.AppVersion .Values.integrationTesting.image.tag | replace "+" "_" }}
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: {{ .Values.integrationTesting.backoffLimit }}
  template:
    metadata:
      name: {{ include "supaglue.componentname" (list . "integration-testing") }}
      labels:
        app.kubernetes.io/name: {{ include "supaglue.name" . }}
        helm.sh/chart: {{ include "supaglue.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ default .Chart.AppVersion .Values.integrationTesting.image.tag | replace "+" "_" }}
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: {{ .Chart.Name }}
    spec:
      {{ include "supaglue.serviceAccount" . }}
      restartPolicy: "OnFailure"
      containers:
        - name: integration-testing
          image: "{{ default "debian:bullseye" .Values.integrationTesting.image.repository }}:{{ default .Chart.AppVersion .Values.integrationTesting.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.integrationTesting.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: production
            {{- with .Values.integrationTesting.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          command: |
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/supaglue-labs/supaglue/dispatches \
              -d '{"event_type":"production_integration_tests"}'
          volumeMounts:
            {{- if .Values.integrationTesting.additionalVolumeMounts }}
            {{- toYaml .Values.integrationTesting.additionalVolumeMounts | nindent 12}}
            {{- end }}
      volumes:
        {{- if .Values.integrationTesting.additionalVolumes }}
        {{- toYaml .Values.integrationTesting.additionalVolumes | nindent 8}}
        {{- end }}
{{ end }}
